devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Alsa
    channels: 2
    device: "hw:CARD=Loopback,DEV=1"
    format: S32_LE
  playback:
    type: Alsa
    channels: 2
    device: "plughw:CARD=Amanero,DEV=0"
    format: S32_LE

filters:
  real_hall_L:
    type: Conv
    parameters:
      type: Wav
      filename: "/home/yasuhito/camilladsp_test/Musikvereinsaal_48k_tail.wav"
      channel: 0
  real_hall_R:
    type: Conv
    parameters:
      type: Wav
      filename: "/home/yasuhito/camilladsp_test/Musikvereinsaal_48k_tail.wav"
      channel: 1
  wet_gain_L:
    type: Gain
    parameters:
      gain: -40
      scale: dB
  wet_gain_R:
    type: Gain
    parameters:
      gain: -40
      scale: dB
  delay_R:
    type: Delay
    parameters:
      delay: 35
      unit: ms
      subsample: false
  high_shelf:
    type: Biquad
    parameters:
      type: Highshelf
      freq: 6000
      slope: 1.0
      gain: -1.5
  safety_limiter:
    type: Limiter
    parameters:
      clip_limit: -0.5
      soft_clip: true

mixers:
  split_2to4:
    channels:
      in: 2
      out: 4
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
      - dest: 2
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 3
        sources:
          - channel: 1
            gain: 0
            inverted: false

  mix_4to2:
    channels:
      in: 4
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
          - channel: 2
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false
          - channel: 3
            gain: 0
            inverted: false

pipeline:
  - type: Mixer
    name: split_2to4
  - type: Filter
    channels: [2]
    names: [real_hall_L, wet_gain_L]
  - type: Filter
    channels: [3]
    names: [real_hall_R, wet_gain_R, delay_R]
  - type: Mixer
    name: mix_4to2
  - type: Filter
    channels: [0, 1]
    names: 
      [
        #high_shelf, 
        safety_limiter
      ]
